#!/usr/bin/env bash
#
# CI gate (AGENTS.md §13): every shipping bundle must declare the same
# marketing version before tagging. macOS app, macOS widget, iOS app, iOS
# widgets, iOS notification service, the four xcodegen MARKETING_VERSIONs,
# AND the watchOS target (whose version is hardcoded in a Ruby script,
# outside project.yml) must all match `App/Info.plist`.
#
# History: 0.5.0 checked only macOS vs iOS MARKETING_VERSION. That let
# 0.7.0 ship with the iOS app + both widget extensions + the watch app
# all stuck at 0.6.x while only the macOS app and project.yml were bumped
# — because those committed Info.plists carry a LITERAL version string and
# the watch version lives in `add_watch_target.rb`. This now checks all of
# them.
#
# NOTE: the iOS Info.plists are generated by xcodegen from
# `AppiOS/project.yml`. When you bump `MARKETING_VERSION` there, run
# `cd AppiOS && xcodegen generate` and commit the regenerated plists so
# the committed tree (what this gate reads) stays in sync.
#
# Exit codes: 0 match · 1 drift · 2 could not read a source.

set -euo pipefail

cd "$(dirname "$0")/.."

mac_plist="App/Info.plist"
if [[ ! -f "$mac_plist" ]]; then
    echo "ERROR: $mac_plist not found" >&2
    exit 2
fi
mac_version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$mac_plist" 2>/dev/null || true)
if [[ -z "$mac_version" ]]; then
    echo "ERROR: could not read CFBundleShortVersionString from $mac_plist" >&2
    exit 2
fi

echo "Reference — macOS $mac_plist CFBundleShortVersionString: $mac_version"
echo

mismatch=0
check() {  # label  value
    local label="$1" value="$2"
    if [[ -z "$value" ]]; then
        printf "  %-54s %s\n" "$label" "(could not read) [ERROR]"
        mismatch=1
    elif [[ "$value" == "$mac_version" ]]; then
        printf "  %-54s %s [OK]\n" "$label" "$value"
    else
        printf "  %-54s %s [MISMATCH]\n" "$label" "$value"
        mismatch=1
    fi
}

# Every committed Info.plist's CFBundleShortVersionString (App/Info.plist
# is the reference, so it's not re-checked here).
for p in \
    App/Widgets/Info.plist \
    AppiOS/Resources/Info.plist \
    AppiOS/Widgets/Info.plist \
    AppiOS/NotificationService/Info.plist
do
    [[ -f "$p" ]] || continue
    check "$p" "$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$p" 2>/dev/null || true)"
done

# Every MARKETING_VERSION in the xcodegen spec (iOS app, Widgets,
# Notification Service, tvOS). Splitting on the double-quote yields the
# quoted value as field 2. Portable on bash 3.2 (macOS system bash).
ios_yml="AppiOS/project.yml"
if [[ -f "$ios_yml" ]]; then
    while IFS= read -r v; do
        [[ -z "$v" ]] && continue
        check "$ios_yml MARKETING_VERSION" "$v"
    done < <(awk -F'"' '/^[[:space:]]*MARKETING_VERSION:/ {print $2}' "$ios_yml")
fi

# watchOS target version — hardcoded in the Ruby script that bolts the
# watch target onto the generated project (it lives outside project.yml,
# so the awk above can't see it).
watch_rb="AppiOS/ci_scripts/add_watch_target.rb"
if [[ -f "$watch_rb" ]]; then
    wv=$(grep -E "bs\['MARKETING_VERSION'\]" "$watch_rb" | sed -E "s/.*=[[:space:]]*'([^']+)'.*/\1/" | head -1)
    check "$watch_rb MARKETING_VERSION" "$wv"
fi

echo
if [[ "$mismatch" -ne 0 ]]; then
    cat >&2 <<EOF
ERROR: version drift. Every shipping bundle must declare $mac_version.
Bump ALL of these together before tagging (AGENTS.md §13):
  - App/Info.plist + App/Widgets/Info.plist (macOS)
  - AppiOS/project.yml MARKETING_VERSIONs (then re-run xcodegen generate)
  - AppiOS/Resources|Widgets|NotificationService/Info.plist (iOS)
  - AppiOS/ci_scripts/add_watch_target.rb (watchOS)
EOF
    exit 1
fi

echo "OK: all version strings match ($mac_version)"
